# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:49:28+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class GetemailinfoGetResponse(BaseModel):
    Code: Optional[str] = None
    Credits: Optional[str] = None
    Email: Optional[str] = None
    Geolocation: Optional[str] = None
    Info: Optional[str] = None
    IsDisposable: Optional[str] = None
    IsEducational: Optional[str] = None
    IsGeneric: Optional[str] = None
    IsGovernment: Optional[str] = None
    IsOrganizational: Optional[str] = None
    IsVulgar: Optional[str] = None
    Response: Optional[str] = None
